# Generated by Django 4.1.1 on 2022-09-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='tax_numer',
            new_name='tax_number',
        ),
    ]
